version: '3.4'

x-postgres-variables: &postgres-variables
  POSTGRES_USER: debug
  POSTGRES_PASSWORD: debug
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: pyoneers_platform
  DATABASE_URL: postgresql://debug:debug@postgres:5432/pyoneers_platform

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      dockerfile: Dockerfile
      args:
        - BUILD_ENVIRONMENT=local
    image: local_django
    container_name: local_django
    environment:
      <<: *postgres-variables
      BUILD_ENVIRONMENT: local
      DJANGO_SETTINGS_MODULE: config.settings.local
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
      DJANGO_SUPERUSER_PASSWORD: admin
      USE_DOCKER: yes
      REDIS_URL: redis://redis:6379/
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    tty: true
    command: /start-django

  postgres:
    image: postgres
    container_name: local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment: *postgres-variables
    ports:
      - "5432:5432"

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: local_redis
