version: '3.4'

x-postgres-variables: &postgres-variables
  POSTGRES_USER: debug
  POSTGRES_PASSWORD: debug
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: pyoneers_platform
  DATABASE_URL: postgresql://debug:debug@postgres:5432/pyoneers_platform

volumes:
  local_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile : ./deployment/local/django/Dockerfile
    image: local_django
    container_name: local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    environment:
      <<: *postgres-variables
      DJANGO_SETTINGS_MODULE: config.settings.local
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
      DJANGO_SUPERUSER_PASSWORD: admin
      USE_DOCKER: yes
      CELERY_BROKER_URL: redis://redis:6379/
      CELERY_FLOWER_USER: debug
      CELERY_FLOWER_PASSWORD: debug
      REDIS_URL: redis://redis:6379/
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres
    container_name: local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment: *postgres-variables

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: local_redis

  celeryworker:
    <<: *django
    image: local_celeryworker
    container_name: local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: local_celerybeat
    container_name: local_celerybeat
    depends_on:
        - redis
        - postgres
        - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: local_flower
    container_name: local_flower
    ports:
      - '5555:5555'
    command: /start-flower
