services:
  - type: web
    name: the-pyoneers-platform-service
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:8000
