#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python << END
import sys
import time

import psycopg
import urllib.parse as urlparse

url = urlparse.urlparse("${DATABASE_URL}")
dbname = url.path[1:]
user = url.username
password = url.password
host = url.hostname
port = url.port

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg.connect(
            dbname=dbname,
            user=user,
            password=password,
            host=host,
            port=port,
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
