# Generated by Django 4.2.5 on 2023-11-12 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0004_chapterfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapterfeedback",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="course.chapter",
                verbose_name="Chapter",
            ),
        ),
        migrations.AlterField(
            model_name="chapterfeedback",
            name="engagement_rating",
            field=models.IntegerField(verbose_name="Engagement"),
        ),
        migrations.AlterField(
            model_name="chapterfeedback",
            name="feedback",
            field=models.TextField(blank=True, verbose_name="Feedback"),
        ),
        migrations.AlterField(
            model_name="chapterfeedback",
            name="practicality_rating",
            field=models.IntegerField(verbose_name="Practicality"),
        ),
        migrations.AlterField(
            model_name="chapterfeedback",
            name="simplicity_rating",
            field=models.IntegerField(verbose_name="Simplicity"),
        ),
        migrations.AlterField(
            model_name="chapterfeedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_feedback",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
