# Generated by Django 4.2.5 on 2023-11-12 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_chapterfeedback_is_anonymous"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapterfeedback",
            name="commit_hash",
        ),
        migrations.AlterField(
            model_name="chapterfeedback",
            name="engagement_rating",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Engagement",
            ),
        ),
        migrations.AlterField(
            model_name="chapterfeedback",
            name="practicality_rating",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Practicality",
            ),
        ),
        migrations.AlterField(
            model_name="chapterfeedback",
            name="simplicity_rating",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Simplicity",
            ),
        ),
    ]
