# Generated by Django 4.2.5 on 2023-11-13 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_remove_chapterfeedback_commit_hash_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="chapterfeedback",
            name="is_anonymous",
        ),
    ]
